# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Proyecto_LP.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import ply



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 350)
        MainWindow.setMinimumSize(QtCore.QSize(450, 350))
        MainWindow.setMaximumSize(QtCore.QSize(1050, 950))
        MainWindow.setStyleSheet("background-color:rgb(28, 105, 157);\n"
"color:white;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Label_title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Label_title.setFont(font)
        self.Label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_title.setObjectName("Label_title")
        self.verticalLayout.addWidget(self.Label_title)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Text_ent = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Text_ent.setStyleSheet("background-color:white;\n"
"color: black;")
        self.Text_ent.setObjectName("Text_ent")
        font.setPointSize(12)
        font.setBold(False)
        self.Text_ent.setFont(font)
        self.horizontalLayout.addWidget(self.Text_ent)
        self.Boton_analizar = QtWidgets.QPushButton(self.centralwidget)
        self.Boton_analizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Boton_analizar.setObjectName("Boton_analizar")
        self.horizontalLayout.addWidget(self.Boton_analizar)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.ListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.ListWidget.setStyleSheet("background-color:white;\n"
"color: black;")
        self.ListWidget.setObjectName("ListWidget")
        self.verticalLayout.addWidget(self.ListWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.verticalLayout.setStretch(0,1)
        self.verticalLayout.setStretch(1,1)
        self.verticalLayout.setStretch(2,10)
        self.Boton_analizar.clicked.connect(self.analizar)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Proyecto - Samira Suárez|David Yánez"))
        self.Label_title.setText(_translate("MainWindow", "Analizador Léxico"))
        self.Boton_analizar.setText(_translate("MainWindow", "Analizar"))

    def analizar(self):
        texto = self.Text_ent.toPlainText()
        self.ListWidget.clear()
        #for i in range(5):
        self.ListWidget.addItems(["Es una variable","No es una palabra reservada","No es una palabra clave conceptual","No es un caracter especial"])





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
